<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CreateLocationsTable extends Migration
{
    public function up()
    {
        Schema::create('locations', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
            $table->string ('province')->nullable();
            $table->string ('city')->nullable();
            $table->string ('address')->nullable();
            $table->string ('plate')->nullable();
            $table->bigInteger('user_id')->nullable()->unsigned();
            $table->bigInteger('agency_id')->nullable()->unsigned();
        });
        //provinces
        Schema::create('provinces', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
        });
        //provinces

        //cities
        Schema::create('cities', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->integer('province_id')->unsigned();
            $table->foreign('province_id')->references('id')->on('provinces')->onDelete('cascade');
        });
        //cities

        //insert provinces
        $provinces=DB::table('provinces')->insert(array(
            array('name'=>'آذربايجان شرقي'),
            array('name'=>'آذربايجان غربي'),
            array('name'=>'اردبيل'),
            array('name'=>'اصفهان'),
            array('name'=>'البرز'),
            array('name'=>'ايلام'),
            array('name'=>'بوشهر'),
            array('name'=>'تهران'),
            array('name'=>'چهارمحال بختياري'),
            array('name'=> 'خراسان جنوبي'),
            array('name'=> 'خراسان رضوي'),
            array('name'=> 'خراسان شمالي'),
            array('name'=> 'خوزستان'),
            array('name'=> 'زنجان'),
            array('name'=> 'سمنان'),
            array('name'=> 'سيستان و بلوچستان'),
            array('name'=> 'فارس'),
            array('name'=> 'قزوين'),
            array('name'=> 'قم'),
            array('name'=> 'كردستان'),
            array('name'=> 'كرمان'),
            array('name'=> 'كرمانشاه'),
            array('name'=> 'كهكيلويه و بويراحمد'),
            array('name'=> 'گلستان'),
            array('name'=> 'گيلان'),
            array('name'=> 'لرستان'),
            array('name'=> 'مازندران'),
            array('name'=> 'مركزي'),
            array('name'=> 'هرمزگان'),
            array('name'=> 'همدان'),
            array('name'=> 'يزد'),
        ));
        //insert provinces

        //insert cities
        $cities=DB::table('cities')->insert(
            array(
                array('province_id'=>1,'name'=>'تبريز'),
                array('province_id'=>2,'name'=>'كندوان'),
                array('province_id'=>3,'name'=>'بندر شرفخانه'),
                array('province_id'=>4,'name'=>'مراغه'),
                array('province_id'=>5,'name'=>'ميانه'),
                array('province_id'=>6,'name'=>'شبستر'),
                array('province_id'=>7,'name'=>'مرند'),
                array('province_id'=>8,'name'=>'جلفا'),
                array('province_id'=>9,'name'=>'سراب'),
                array('province_id'=>1,'name'=> 'هاديشهر'),
                array('province_id'=>1,'name'=> 'بناب'),
                array('province_id'=>1,'name'=> 'كليبر'),
                array('province_id'=>1,'name'=> 'تسوج'),
                array('province_id'=>1,'name'=> 'اهر'),
                array('province_id'=>1,'name'=> 'هريس'),
                array('province_id'=>1,'name'=> 'عجبشير'),
                array('province_id'=>1,'name'=> 'هشترود'),
                array('province_id'=>1,'name'=> 'ملكان'),
                array('province_id'=>1,'name'=> 'بستان آباد'),
                array('province_id'=>1,'name'=> 'ورزقان'),
                array('province_id'=>1,'name'=> 'اسكو'),
                array('province_id'=>1,'name'=> 'آذر شهر'),
                array('province_id'=>1,'name'=> 'قره آغاج'),
                array('province_id'=>1,'name'=> 'ممقان'),
                array('province_id'=>1,'name'=> 'صوفیان'),
                array('province_id'=>1,'name'=> 'ایلخچی'),
                array('province_id'=>1,'name'=> 'خسروشهر'),
                array('province_id'=>1,'name'=> 'باسمنج'),
                array('province_id'=>1,'name'=> 'سهند'),
                array('province_id'=>2,'name'=> 'اروميه'),
                array('province_id'=>2,'name'=> 'نقده'),
                array('province_id'=>2,'name'=> 'ماكو'),
                array('province_id'=>2,'name'=> 'تكاب'),
                array('province_id'=>2,'name'=> 'خوي'),
                array('province_id'=>2,'name'=> 'مهاباد'),
                array('province_id'=>2,'name'=> 'سر دشت'),
                array('province_id'=>2,'name'=> 'چالدران'),
                array('province_id'=>2,'name'=> 'بوكان'),
                array('province_id'=>2,'name'=> 'مياندوآب'),
                array('province_id'=>2,'name'=> 'سلماس'),
                array('province_id'=>2,'name'=> 'شاهين دژ'),
                array('province_id'=>2,'name'=> 'پيرانشهر'),
                array('province_id'=>2,'name'=> 'سيه چشمه'),
                array('province_id'=>2,'name'=> 'اشنويه'),
                array('province_id'=>2,'name'=> 'چایپاره'),
                array('province_id'=>2,'name'=> 'پلدشت'),
                array('province_id'=>2,'name'=> 'شوط'),
                array('province_id'=>3,'name'=> 'اردبيل'),
                array('province_id'=>3,'name'=> 'سرعين'),
                array('province_id'=>3,'name'=> 'بيله سوار'),
                array('province_id'=>3,'name'=> 'پارس آباد'),
                array('province_id'=>3,'name'=> 'خلخال'),
                array('province_id'=>3,'name'=> 'مشگين شهر'),
                array('province_id'=>3,'name'=> 'مغان'),
                array('province_id'=>3,'name'=> 'نمين'),
                array('province_id'=>3,'name'=> 'نير'),
                array('province_id'=>3,'name'=> 'كوثر'),
                array('province_id'=>3,'name'=> 'كيوي'),
                array('province_id'=>3,'name'=> 'گرمي'),
                array('province_id'=>4,'name'=> 'اصفهان'),
                array('province_id'=>4,'name'=> 'فريدن'),
                array('province_id'=>4,'name'=> 'فريدون شهر'),
                array('province_id'=>4,'name'=> 'فلاورجان'),
                array('province_id'=>4,'name'=> 'گلپايگان'),
                array('province_id'=>4,'name'=> 'دهاقان'),
                array('province_id'=>4,'name'=> 'نطنز'),
                array('province_id'=>4,'name'=> 'نايين'),
                array('province_id'=>4,'name'=> 'تيران'),
                array('province_id'=>4,'name'=> 'كاشان'),
                array('province_id'=>4,'name'=> 'فولاد شهر'),
                array('province_id'=>4,'name'=> 'اردستان'),
                array('province_id'=>4,'name'=> 'سميرم'),
                array('province_id'=>4,'name'=> 'درچه'),
                array('province_id'=>4,'name'=> 'کوهپایه'),
                array('province_id'=>4,'name'=> 'مباركه'),
                array('province_id'=>4,'name'=> 'شهرضا'),
                array('province_id'=>4,'name'=> 'خميني شهر'),
                array('province_id'=>4,'name'=> 'شاهين شهر'),
                array('province_id'=>4,'name'=> 'نجف آباد'),
                array('province_id'=>4,'name'=> 'دولت آباد'),
                array('province_id'=>4,'name'=> 'زرين شهر'),
                array('province_id'=>4,'name'=> 'آران و بيدگل'),
                array('province_id'=>4,'name'=> 'باغ بهادران'),
                array('province_id'=>4,'name'=> 'خوانسار'),
                array('province_id'=>4,'name'=> 'مهردشت'),
                array('province_id'=>4,'name'=> 'علويجه'),
                array('province_id'=>4,'name'=> 'عسگران'),
                array('province_id'=>4,'name'=> 'نهضت آباد'),
                array('province_id'=>4,'name'=> 'حاجي آباد'),
                array('province_id'=>4,'name'=> 'تودشک'),
                array('province_id'=>4,'name'=> 'ورزنه'),
                array('province_id'=>5,'name'=>'طالقان'),
                array('province_id'=>5,'name'=>'نظرآباد'),
                array('province_id'=>5,'name'=>'اشتهارد'),
                array('province_id'=>5,'name'=>'هشتگرد'),
                array('province_id'=>5,'name'=>'كن'),
                array('province_id'=>5,'name'=>'آسارا'),
                array('province_id'=>5,'name'=>'شهرک گلستان'),
                array('province_id'=>5,'name'=>'اندیشه'),
                array('province_id'=>5,'name'=>'كرج'),
                array('province_id'=>5,'name'=>'نظر آباد'),
                array('province_id'=>5,'name'=>'گوهردشت'),
                array('province_id'=>5,'name'=>'ماهدشت'),
                array('province_id'=>5,'name'=>'مشکین دشت'),
                array('province_id'=>6,'name'=> 'ايلام'),
                array('province_id'=>6,'name'=> 'مهران'),
                array('province_id'=>6,'name'=> 'دهلران'),
                array('province_id'=>6,'name'=> 'آبدانان'),
                array('province_id'=>6,'name'=> 'شيروان چرداول'),
                array('province_id'=>6,'name'=> 'دره شهر'),
                array('province_id'=>6,'name'=> 'ايوان'),
                array('province_id'=>6,'name'=> 'سرابله'),
                array('province_id'=>7,'name'=>'بوشهر'),
                array('province_id'=>7,'name'=>'تنگستان'),
                array('province_id'=>7,'name'=>'دشتستان'),
                array('province_id'=>7,'name'=>'دير'),
                array('province_id'=>7,'name'=>'ديلم'),
                array('province_id'=>7,'name'=>'كنگان'),
                array('province_id'=>7,'name'=>'گناوه'),
                array('province_id'=>7,'name'=>'ريشهر'),
                array('province_id'=>7,'name'=>'دشتي'),
                array('province_id'=>7,'name'=>'خورموج'),
                array('province_id'=>7,'name'=>'اهرم'),
                array('province_id'=>7,'name'=>'برازجان'),
                array('province_id'=>7,'name'=>'خارك'),
                array('province_id'=>7,'name'=>'جم'),
                array('province_id'=>7,'name'=>'کاکی'),
                array('province_id'=>7,'name'=>'عسلویه'),
                array('province_id'=>7,'name'=>'بردخون'),
                array('province_id'=>8,'name'=>'تهران'),
                array('province_id'=>8,'name'=>'ورامين'),
                array('province_id'=>8,'name'=>'فيروزكوه'),
                array('province_id'=>8,'name'=>'ري'),
                array('province_id'=>8,'name'=>'دماوند'),
                array('province_id'=>8,'name'=>'اسلامشهر'),
                array('province_id'=>8,'name'=>'رودهن'),
                array('province_id'=>8,'name'=>'لواسان'),
                array('province_id'=>8,'name'=>'بومهن'),
                array('province_id'=>8,'name'=>'تجريش'),
                array('province_id'=>8,'name'=>'فشم'),
                array('province_id'=>8,'name'=>'كهريزك'),
                array('province_id'=>8,'name'=>'پاكدشت'),
                array('province_id'=>8,'name'=>'چهاردانگه'),
                array('province_id'=>8,'name'=>'شريف آباد'),
                array('province_id'=>8,'name'=>'قرچك'),
                array('province_id'=>8,'name'=>'باقرشهر'),
                array('province_id'=>8,'name'=>'شهريار'),
                array('province_id'=>8,'name'=>'رباط كريم'),
                array('province_id'=>8,'name'=>'قدس'),
                array('province_id'=>8,'name'=>'ملارد'),
                array('province_id'=>9,'name'=>'شهركرد'),
                array('province_id'=>9,'name'=>'فارسان'),
                array('province_id'=>9,'name'=>'بروجن'),
                array('province_id'=>9,'name'=>'چلگرد'),
                array('province_id'=>9,'name'=>'اردل'),
                array('province_id'=>9,'name'=>'لردگان'),
                array('province_id'=>9,'name'=>'سامان'),
                array('province_id'=>10,'name'=>'قائن'),
                array('province_id'=>10,'name'=>'فردوس'),
                array('province_id'=>10,'name'=>'بيرجند'),
                array('province_id'=>10,'name'=>'نهبندان'),
                array('province_id'=>10,'name'=>'سربيشه'),
                array('province_id'=>10,'name'=>'طبس مسینا'),
                array('province_id'=>10,'name'=>'قهستان'),
                array('province_id'=>10,'name'=>'درمیان'),
                array('province_id'=>11,'name'=>'مشهد'),
                array('province_id'=>11,'name'=>'نيشابور'),
                array('province_id'=>11,'name'=>'سبزوار'),
                array('province_id'=>11,'name'=>'كاشمر'),
                array('province_id'=>11,'name'=>'گناباد'),
                array('province_id'=>11,'name'=>'طبس'),
                array('province_id'=>11,'name'=>'تربت حيدريه'),
                array('province_id'=>11,'name'=>'خواف'),
                array('province_id'=>11,'name'=>'تربت جام'),
                array('province_id'=>11,'name'=>'تايباد'),
                array('province_id'=>11,'name'=>'قوچان'),
                array('province_id'=>11,'name'=>'سرخس'),
                array('province_id'=>11,'name'=>'بردسكن'),
                array('province_id'=>11,'name'=>'فريمان'),
                array('province_id'=>11,'name'=>'چناران'),
                array('province_id'=>11,'name'=>'درگز'),
                array('province_id'=>11,'name'=>'كلات'),
                array('province_id'=>11,'name'=>'طرقبه'),
                array('province_id'=>11,'name'=>'سر ولایت'),
                array('province_id'=>12,'name'=>'بجنورد'),
                array('province_id'=>12,'name'=>'اسفراين'),
                array('province_id'=>12,'name'=>'جاجرم'),
                array('province_id'=>12,'name'=>'شيروان'),
                array('province_id'=>12,'name'=>'آشخانه'),
                array('province_id'=>12,'name'=>'گرمه'),
                array('province_id'=>12,'name'=>'ساروج'),
                array('province_id'=>13,'name'=>'اهواز'),
                array('province_id'=>13,'name'=>'ايرانشهر'),
                array('province_id'=>13,'name'=>'شوش'),
                array('province_id'=>13,'name'=>'آبادان'),
                array('province_id'=>13,'name'=>'خرمشهر'),
                array('province_id'=>13,'name'=>'مسجد سليمان'),
                array('province_id'=>13,'name'=>'ايذه'),
                array('province_id'=>13,'name'=>'شوشتر'),
                array('province_id'=>13,'name'=>'انديمشك'),
                array('province_id'=>13,'name'=>'سوسنگرد'),
                array('province_id'=>13,'name'=>'هويزه'),
                array('province_id'=>13,'name'=>'دزفول'),
                array('province_id'=>13,'name'=>'شادگان'),
                array('province_id'=>13,'name'=>'بندر ماهشهر'),
                array('province_id'=>13,'name'=>'بندر امام خميني'),
                array('province_id'=>13,'name'=>'اميديه'),
                array('province_id'=>13,'name'=>'بهبهان'),
                array('province_id'=>13,'name'=>'رامهرمز'),
                array('province_id'=>13,'name'=>'باغ ملك'),
                array('province_id'=>13,'name'=>'هنديجان'),
                array('province_id'=>13,'name'=>'لالي'),
                array('province_id'=>13,'name'=>'رامشیر'),
                array('province_id'=>13,'name'=>'حمیدیه'),
                array('province_id'=>13,'name'=>'دغاغله'),
                array('province_id'=>13,'name'=>'ملاثانی'),
                array('province_id'=>13,'name'=>'شادگان'),
                array('province_id'=>13,'name'=>'ویسی'),
                array('province_id'=>14,'name'=>'زنجان'),
                array('province_id'=>14,'name'=>'ابهر'),
                array('province_id'=>14,'name'=>'خدابنده'),
                array('province_id'=>14,'name'=>'طارم'),
                array('province_id'=>14,'name'=>'ماهنشان'),
                array('province_id'=>14,'name'=>'خرمدره'),
                array('province_id'=>14,'name'=>'ايجرود'),
                array('province_id'=>14,'name'=>'زرين آباد'),
                array('province_id'=>14,'name'=>'آب بر'),
                array('province_id'=>14,'name'=>'قيدار'),
                array('province_id'=>15,'name'=>'سمنان'),
                array('province_id'=>15,'name'=>'شاهرود'),
                array('province_id'=>15,'name'=>'گرمسار'),
                array('province_id'=>15,'name'=>'ايوانكي'),
                array('province_id'=>15,'name'=>'دامغان'),
                array('province_id'=>15,'name'=>'بسطام'),
                array('province_id'=>16,'name'=>'زاهدان'),
                array('province_id'=>16,'name'=>'چابهار'),
                array('province_id'=>16,'name'=>'خاش'),
                array('province_id'=>16,'name'=>'سراوان'),
                array('province_id'=>16,'name'=>'زابل'),
                array('province_id'=>16,'name'=>'سرباز'),
                array('province_id'=>16,'name'=>'نيكشهر'),
                array('province_id'=>16,'name'=>'ايرانشهر'),
                array('province_id'=>16,'name'=>'راسك'),
                array('province_id'=>16,'name'=>'ميرجاوه'),
                array('province_id'=>17,'name'=>'شيراز'),
                array('province_id'=>17,'name'=>'اقليد'),
                array('province_id'=>17,'name'=>'داراب'),
                array('province_id'=>17,'name'=>'فسا'),
                array('province_id'=>17,'name'=>'مرودشت'),
                array('province_id'=>17,'name'=>'خرم بيد'),
                array('province_id'=>17,'name'=>'آباده'),
                array('province_id'=>17,'name'=>'كازرون'),
                array('province_id'=>17,'name'=>'ممسني'),
                array('province_id'=>17,'name'=>'سپيدان'),
                array('province_id'=>17,'name'=>'لار'),
                array('province_id'=>17,'name'=>'فيروز آباد'),
                array('province_id'=>17,'name'=>'جهرم'),
                array('province_id'=>17,'name'=>'ني ريز'),
                array('province_id'=>17,'name'=>'استهبان'),
                array('province_id'=>17,'name'=>'لامرد'),
                array('province_id'=>17,'name'=>'مهر'),
                array('province_id'=>17,'name'=>'حاجي آباد'),
                array('province_id'=>17,'name'=>'نورآباد'),
                array('province_id'=>17,'name'=>'اردكان'),
                array('province_id'=>17,'name'=>'صفاشهر'),
                array('province_id'=>17,'name'=>'ارسنجان'),
                array('province_id'=>17,'name'=>'قيروكارزين'),
                array('province_id'=>17,'name'=>'سوريان'),
                array('province_id'=>17,'name'=>'فراشبند'),
                array('province_id'=>17,'name'=>'سروستان'),
                array('province_id'=>17,'name'=>'ارژن'),
                array('province_id'=>17,'name'=>'گويم'),
                array('province_id'=>17,'name'=>'داريون'),
                array('province_id'=>17,'name'=>'زرقان'),
                array('province_id'=>17,'name'=>'خان زنیان'),
                array('province_id'=>17,'name'=>'کوار'),
                array('province_id'=>17,'name'=>'ده بید'),
                array('province_id'=>17,'name'=>'باب انار/خفر'),
                array('province_id'=>17,'name'=>'بوانات'),
                array('province_id'=>17,'name'=>'خرامه'),
                array('province_id'=>17,'name'=>'خنج'),
                array('province_id'=>17,'name'=>'سیاخ دارنگون'),
                array('province_id'=>18,'name'=>'قزوين'),
                array('province_id'=>18,'name'=>'تاكستان'),
                array('province_id'=>18,'name'=>'آبيك'),
                array('province_id'=>18,'name'=>'بوئين زهرا'),
                array('province_id'=>19,'name'=>'قم'),
                array('province_id'=>20,'name'=>'سنندج'),
                array('province_id'=>20,'name'=>'ديواندره'),
                array('province_id'=>20,'name'=>'بانه'),
                array('province_id'=>20,'name'=>'بيجار'),
                array('province_id'=>20,'name'=>'سقز'),
                array('province_id'=>20,'name'=>'كامياران'),
                array('province_id'=>20,'name'=>'قروه'),
                array('province_id'=>20,'name'=>'مريوان'),
                array('province_id'=>20,'name'=>'صلوات آباد'),
                array('province_id'=>20,'name'=>'حسن آباد'),
                array('province_id'=>21,'name'=>'كرمان'),
                array('province_id'=>21,'name'=>'راور'),
                array('province_id'=>21,'name'=>'بابك'),
                array('province_id'=>21,'name'=>'انار'),
                array('province_id'=>21,'name'=>'کوهبنان'),
                array('province_id'=>21,'name'=>'رفسنجان'),
                array('province_id'=>21,'name'=>'بافت'),
                array('province_id'=>21,'name'=>'سيرجان'),
                array('province_id'=>21,'name'=>'كهنوج'),
                array('province_id'=>21,'name'=>'زرند'),
                array('province_id'=>21,'name'=>'بم'),
                array('province_id'=>21,'name'=>'جيرفت'),
                array('province_id'=>21,'name'=>'بردسير'),
                array('province_id'=>22,'name'=>'كرمانشاه'),
                array('province_id'=>22,'name'=>'اسلام آباد غرب'),
                array('province_id'=>22,'name'=>'سر پل ذهاب'),
                array('province_id'=>22,'name'=>'كنگاور'),
                array('province_id'=>22,'name'=>'سنقر'),
                array('province_id'=>22,'name'=>'قصر شيرين'),
                array('province_id'=>22,'name'=>'گيلان غرب'),
                array('province_id'=>22,'name'=>'هرسين'),
                array('province_id'=>22,'name'=>'صحنه'),
                array('province_id'=>22,'name'=>'پاوه'),
                array('province_id'=>22,'name'=>'جوانرود'),
                array('province_id'=>22,'name'=>'شاهو'),
                array('province_id'=>23,'name'=>'ياسوج'),
                array('province_id'=>23,'name'=>'گچساران'),
                array('province_id'=>23,'name'=>'دنا'),
                array('province_id'=>23,'name'=>'دوگنبدان'),
                array('province_id'=>23,'name'=>'سي سخت'),
                array('province_id'=>23,'name'=>'دهدشت'),
                array('province_id'=>23,'name'=>'ليكك'),
                array('province_id'=>24,'name'=>'گرگان'),
                array('province_id'=>24,'name'=>'آق قلا'),
                array('province_id'=>24,'name'=>'گنبد كاووس'),
                array('province_id'=>24,'name'=>'علي آباد كتول'),
                array('province_id'=>24,'name'=>'مينو دشت'),
                array('province_id'=>24,'name'=>'تركمن'),
                array('province_id'=>24,'name'=>'كردكوي'),
                array('province_id'=>24,'name'=>'بندر گز'),
                array('province_id'=>24,'name'=>'كلاله'),
                array('province_id'=>24,'name'=>'آزاد شهر'),
                array('province_id'=>24,'name'=>'راميان'),
                array('province_id'=>25,'name'=>'رشت'),
                array('province_id'=>25,'name'=>'منجيل'),
                array('province_id'=>25,'name'=>'لنگرود'),
                array('province_id'=>25,'name'=>'رود سر'),
                array('province_id'=>25,'name'=>'تالش'),
                array('province_id'=>25,'name'=>'آستارا'),
                array('province_id'=>25,'name'=>'ماسوله'),
                array('province_id'=>25,'name'=>'آستانه اشرفيه'),
                array('province_id'=>25,'name'=>'رودبار'),
                array('province_id'=>25,'name'=>'فومن'),
                array('province_id'=>25,'name'=>'صومعه سرا'),
                array('province_id'=>25,'name'=>'بندرانزلي'),
                array('province_id'=>25,'name'=>'كلاچاي'),
                array('province_id'=>25,'name'=>'هشتپر'),
                array('province_id'=>25,'name'=>'رضوان شهر'),
                array('province_id'=>25,'name'=>'ماسال'),
                array('province_id'=>25,'name'=>'شفت'),
                array('province_id'=>25,'name'=>'سياهكل'),
                array('province_id'=>25,'name'=>'املش'),
                array('province_id'=>25,'name'=>'لاهیجان'),
                array('province_id'=>25,'name'=>'خشک بيجار'),
                array('province_id'=>25,'name'=>'خمام'),
                array('province_id'=>25,'name'=>'لشت نشا'),
                array('province_id'=>25,'name'=>'بندر کياشهر'),
                array('province_id'=>26,'name'=>'خرم آباد'),
                array('province_id'=>26,'name'=>'ماهشهر'),
                array('province_id'=>26,'name'=>'دزفول'),
                array('province_id'=>26,'name'=>'بروجرد'),
                array('province_id'=>26,'name'=>'دورود'),
                array('province_id'=>26,'name'=>'اليگودرز'),
                array('province_id'=>26,'name'=>'ازنا'),
                array('province_id'=>26,'name'=>'نور آباد'),
                array('province_id'=>26,'name'=>'كوهدشت'),
                array('province_id'=>26,'name'=>'الشتر'),
                array('province_id'=>26,'name'=>'پلدختر'),
                array('province_id'=>27,'name'=>'ساري'),
                array('province_id'=>27,'name'=>'آمل'),
                array('province_id'=>27,'name'=>'بابل'),
                array('province_id'=>27,'name'=>'بابلسر'),
                array('province_id'=>27,'name'=>'بهشهر'),
                array('province_id'=>27,'name'=>'تنكابن'),
                array('province_id'=>27,'name'=>'جويبار'),
                array('province_id'=>27,'name'=>'چالوس'),
                array('province_id'=>27,'name'=>'رامسر'),
                array('province_id'=>27,'name'=>'سواد كوه'),
                array('province_id'=>27,'name'=>'قائم شهر'),
                array('province_id'=>27,'name'=>'نكا'),
                array('province_id'=>27,'name'=>'نور'),
                array('province_id'=>27,'name'=>'بلده'),
                array('province_id'=>27,'name'=>'نوشهر'),
                array('province_id'=>27,'name'=>'پل سفيد'),
                array('province_id'=>27,'name'=>'محمود آباد'),
                array('province_id'=>27,'name'=>'فريدون كنار'),
                array('province_id'=>28,'name'=>'اراك'),
                array('province_id'=>28,'name'=>'آشتيان'),
                array('province_id'=>28,'name'=>'تفرش'),
                array('province_id'=>28,'name'=>'خمين'),
                array('province_id'=>28,'name'=>'دليجان'),
                array('province_id'=>28,'name'=>'ساوه'),
                array('province_id'=>28,'name'=>'سربند'),
                array('province_id'=>28,'name'=>'محلات'),
                array('province_id'=>28,'name'=>'شازند'),
                array('province_id'=>29,'name'=>'بندرعباس'),
                array('province_id'=>29,'name'=>'قشم'),
                array('province_id'=>29,'name'=>'كيش'),
                array('province_id'=>29,'name'=>'بندر لنگه'),
                array('province_id'=>29,'name'=>'بستك'),
                array('province_id'=>29,'name'=>'حاجي آباد'),
                array('province_id'=>29,'name'=>'دهبارز'),
                array('province_id'=>29,'name'=>'انگهران'),
                array('province_id'=>29,'name'=>'ميناب'),
                array('province_id'=>29,'name'=>'ابوموسي'),
                array('province_id'=>29,'name'=>'بندر جاسك'),
                array('province_id'=>29,'name'=>'تنب بزرگ'),
                array('province_id'=>29,'name'=>'بندر خمیر'),
                array('province_id'=>29,'name'=>'پارسیان'),
                array('province_id'=>29,'name'=>'قشم'),
                array('province_id'=>30,'name'=>'همدان'),
                array('province_id'=>30,'name'=>'ملاير'),
                array('province_id'=>30,'name'=>'تويسركان'),
                array('province_id'=>30,'name'=>'نهاوند'),
                array('province_id'=>30,'name'=>'كبودر اهنگ'),
                array('province_id'=>30,'name'=>'رزن'),
                array('province_id'=>30,'name'=>'اسدآباد'),
                array('province_id'=>30,'name'=>'بهار'),
                array('province_id'=>31,'name'=>'يزد'),
                array('province_id'=>31,'name'=>'تفت'),
                array('province_id'=>31,'name'=>'اردكان'),
                array('province_id'=>31,'name'=>'ابركوه'),
                array('province_id'=>31,'name'=>'ميبد'),
                array('province_id'=>31,'name'=>'طبس'),
                array('province_id'=>31,'name'=>'بافق'),
                array('province_id'=>31,'name'=>'مهريز'),
                array('province_id'=>31,'name'=>'اشكذر'),
                array('province_id'=>31,'name'=>'هرات'),
                array('province_id'=>31,'name'=>'خضرآباد'),
                array('province_id'=>31,'name'=>'شاهديه'),
                array('province_id'=>31,'name'=>'حمیدیه شهر'),
                array('province_id'=>31,'name'=>'سید میرزا'),
                array('province_id'=>31,'name'=>'زارچ')
            )
        );
        //insert cities
    }

    public function down()
    {
        Schema::dropIfExists('locations');
        Schema::dropIfExists('cities');
        Schema::dropIfExists('provinces');
    }
}
